### ISSUE TITLE
Reviews 1

### ISSUE THREAD

**Issue by danielleaop** [SchoolOfCode/bc17-w7d3-workshop-nextjs-boilerplate-brave-terrible-beachball#1]
```[tasklist]
### Tasks
- [x] create heading html tag
- [ ] create horizontal grey line
- [x] create subheading text box thing
- [x] style these elements in css
```
